"""Initial migration - create request_history table

Revision ID: c48a9029ad04
Revises: 
Create Date: 2025-12-13 16:58:38.869408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48a9029ad04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('heart_axis', sa.String(length=20), nullable=False),
    sa.Column('predicted_class_index', sa.Integer(), nullable=True),
    sa.Column('predicted_class_name', sa.String(length=50), nullable=True),
    sa.Column('predicted_class_description', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_history')
    # ### end Alembic commands ###
